name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: yarn

      - name: corepack enable
        shell: bash
        run: corepack enable

      - name: install dependencies
        shell: bash
        run: yarn install

      - name: setup nx shas
        uses: nrwl/nx-set-shas@v4

      - name: lint
        run: yarn nx affected --target lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: yarn

      - name: Docker Setup
        if: github.ref == 'refs/heads/develop'
        uses: ./.github/actions/setup-docker

      - name: corepack enable
        shell: bash
        run: corepack enable

      - name: install dependencies
        shell: bash
        run: yarn install

      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: .docker
          key: ${{ runner.os }}-docker-layers

      - name: setup nx shas
        uses: nrwl/nx-set-shas@v4

      - name: test
        run: yarn nx affected --target test --parallel 1

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: yarn

      - name: Docker Setup
        if: github.ref == 'refs/heads/develop'
        uses: ./.github/actions/setup-docker
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: corepack enable
        shell: bash
        run: corepack enable

      - name: install dependencies
        shell: bash
        run: yarn install

      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: .docker
          key: ${{ runner.os }}-docker-layers

      - name: Build & Push Docker Image
        run: yarn nx run-many --target docker-push
